# Generated by Django 4.2.16 on 2024-11-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_panier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='commandes',
            field=models.ManyToManyField(related_name='panier', to='boutique.commande'),
        ),
    ]
