# Generated by Django 4.2.16 on 2024-11-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_alter_panier_commandes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='commande',
            new_name='commandé',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='commandé',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='date_commande',
        ),
        migrations.AddField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
